### ISSUE TITLE
Array size mismatch during validation (dataset.py line 197)

### ISSUE THREAD

**Issue by max-krichenbauer** [funcwj/deep-clustering#11]
Hello and thank you for providing the source code!

For me, it always crashes during validation:

```
2020-03-12 14:55:30,998 [/home/me/deep-clustering/trainer.py:85 - INFO ] Evaluating...
Traceback (most recent call last):
  File "./train_dcnet.py", line 90, in <module>
    train(args)
  File "./train_dcnet.py", line 65, in train
    trainer.run(train_loader, valid_loader, num_epoches=args.num_epoches)
  File "/home/me/deep-clustering/trainer.py", line 102, in run
    init_loss, _ = self.validate(dev_set)
  File "/home/me/deep-clustering/trainer.py", line 90, in validate
    for mix_spect, tgt_index, vad_masks in dataloader:
  File "/home/me/deep-clustering/dataset.py", line 239, in __iter__
    yield self._process(index)
  File "/home/me/deep-clustering/dataset.py", line 219, in _process
    data_dict = self._transform(s, t)
  File "/home/me/deep-clustering/dataset.py", line 197, in _transform
    target_attr = np.argmax(np.array(targets_specs_list), 0)
  File "/home/me/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 963, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/me/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: operands could not be broadcast together with shapes (680,129) (356,129)
```

The type of mismatch (here: 680 and 356) depends on the sample set used, but there is always a mismatch that causes the crash.

What could be the reason?

Thank you!

**Comment by max-krichenbauer** [comment]
Found the reason: some of the audio files differed in length (duration) between speaker1, speaker2 and the mixed audio.
