### ISSUE TITLE
TypeError: '<=' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by aishoot** [funcwj/deep-clustering#3]
嗨，您好，可以麻烦您再帮我看下两个问题么：
1. "cmvn.dict"是只需要计算训练集"tr"下的mixture还是"tr/cv/tt"三个文件夹的mixture一起计算？
2. 就是题目所示的bug，pyTorch的版本我跟您的保持一致0.4.0，升级到最新版也是同样的错误，完整的报错如下：
```
2019-04-27 22:48:06,634 [/home/MyCode/DeepClustering/funcwj_deep-clustering/trainer.py:43 - INFO ] DCNet:
DCNet(
  (rnn): LSTM(129, 600, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (drops): Dropout(p=0.5)
  (embed): Linear(in_features=1200, out_features=2580, bias=True)
)
Traceback (most recent call last):
  File "./train_dcnet.py", line 80, in <module>
    train(args)
  File "./train_dcnet.py", line 54, in train
    trainer = Trainer(dcnet, **config_dict["trainer"])
  File "/home/MyCode/DeepClustering/funcwj_deep-clustering/trainer.py", line 49, in __init__
    weight_decay=weight_decay)
  File "/home/MyCode/DeepClustering/funcwj_deep-clustering/trainer.py", line 27, in create_optimizer
    opt = supported_optimizer[optimizer](params, **kwargs)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/optim/rmsprop.py", line 29, in __init__
    if not 0.0 <= lr:
TypeError: '<=' not supported between instances of 'float' and 'str'
```

**Comment by funcwj** [comment]
1. "cmvn.dict"只在训练集上计算
2. 这个可能是yaml配置的问题，科学计数法可能区分不了浮点数和字符，lr写成"1.0e-5"试试？

**Comment by aishoot** [comment]
确实是这样，非常感谢～

**Comment by funcwj** [comment]
不过这个代码实现的有点久了，不少地方换种写法应该更好，我后面也没有重新跟进。

**Comment by aishoot** [comment]
辛苦老铁了
