### ISSUE TITLE
请问数据集在哪里获取？

### ISSUE THREAD

**Issue by Fanghc95** [funcwj/deep-clustering#5]
配置文件里的scp是文件路径 ，请问数据集在哪里获取，或使用的那个数据集？

**Comment by funcwj** [comment]
原版论文使用的数据集创建代码在这里[create-speaker-mixtures.zip](http://www.merl.com/demos/deep-clustering/create-speaker-mixtures.zip)，但是考虑到你可能没有wsj0数据，因此建议你自己选一个clean的数据集simulation，比如librispeech等等。

**Comment by Fanghc95** [comment]
感谢

**Comment by Fanghc95** [comment]
请问一下，cmvn.dict 是什么。训练时没有这个文件，.scp的已经弄好了

**Comment by funcwj** [comment]
可以通过compute_cmvn.py计算得到，一个存储均值和方差的字典，用于均值方差归一化

**Comment by Fanghc95** [comment]
使用了VOX1数据集，单声道16000帧率，训练时报错
`2019-06-05 17:32:48,973 [F:\speaker\VGG-Speaker-Recognition-master\meta\trainer.py:85 - INFO ] Evaluating...
Traceback (most recent call last):
  File "F:/speaker/VGG-Speaker-Recognition-master/meta/train_dcnet.py", line 90, in <module>
    train(args)
  File "F:/speaker/VGG-Speaker-Recognition-master/meta/train_dcnet.py", line 65, in train
    trainer.run(train_loader, valid_loader, num_epoches=args.num_epoches)
  File "F:\speaker\VGG-Speaker-Recognition-master\meta\trainer.py", line 102, in run
    init_loss, _ = self.validate(dev_set)
  File "F:\speaker\VGG-Speaker-Recognition-master\meta\trainer.py", line 90, in validate
    for mix_spect, tgt_index, vad_masks in dataloader:
  File "F:\speaker\VGG-Speaker-Recognition-master\meta\dataset.py", line 239, in __iter__
    yield self._process(index)
  File "F:\speaker\VGG-Speaker-Recognition-master\meta\dataset.py", line 219, in _process
    data_dict = self._transform(s, t)
  File "F:\speaker\VGG-Speaker-Recognition-master\meta\dataset.py", line 197, in _transform
    target_attr = np.argmax(np.array(targets_specs_list), 0)
  File "C:\ProgramData\Anaconda3\envs\speaker\lib\site-packages\numpy\core\fromnumeric.py", line 963, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "C:\ProgramData\Anaconda3\envs\speaker\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: operands could not be broadcast together with shapes (2787,129) (1637,129) `

**Comment by funcwj** [comment]
你spk1，spk2，mix的句子长度一样吗

**Comment by Fanghc95** [comment]
已经开始训练了，请问默认是GPU训练么。我训练时没有用到GPU资源。我是Windows系统单显卡，代码中cuda:0需要修改吗？

**Comment by Fanghc95** [comment]
> 你spk1，spk2，mix的句子长度一样吗

解决了，感谢，调整了长度
